### ISSUE TITLE
about the picture

### ISSUE THREAD

**Issue by lxsy-xcy** [Lifelong-Robot-Learning/LIBERO#13]
Thanks for this wonderful benchmark.
I'm a bit confused, are these two parts written in reverse?
![1706188443905](https://github.com/Lifelong-Robot-Learning/LIBERO/assets/72680226/defd0741-6c67-40ad-bf8b-d46c726c9157)

**Comment by Cranial-XIX** [comment]
Thanks for catching that... it is indeed a typo.
