### ISSUE TITLE
the version numbers of robosuite ? 

### ISSUE THREAD

**Issue by BrightMoonStar** [Lifelong-Robot-Learning/LIBERO#18]
Could you please provide the version numbers of robosuite ?  I learned that robosuite has undergone major changes in versions 1.3 and 1.4, which may cause data sets to mismatch.  
Thanks a lot!
https://github.com/UT-Austin-RPL/VIOLA#dataset-and-trained-checkpoints  
 https://github.com/ARISE-Initiative/robosuite-task-zoo/issues/5#issuecomment-1965706715
![image](https://github.com/Lifelong-Robot-Learning/LIBERO/assets/144759751/8701d0a1-5758-4653-8019-159003d1f3da)
![image](https://github.com/Lifelong-Robot-Learning/LIBERO/assets/144759751/6dce19d6-7ba2-49fa-bda3-89b5bd9b4b96)

**Comment by Cranial-XIX** [comment]
LIBERO is compatible with v1.4.0 so no worries :)

**Comment by BrightMoonStar** [comment]
Thanks for your reply !
