### ISSUE TITLE
How to use the custom robot?

### ISSUE THREAD

**Issue by chiawenwang** [Lifelong-Robot-Learning/LIBERO#22]
Hi! Thank you for your source code! It's really good and I wonder how to use the custom robot in LIBERO? Is there any instructions?

**Comment by Cranial-XIX** [comment]
Thanks for your interest in our work :) We do not support customized robots at the time, but as the code is based on [Robosuite](https://robosuite.ai/docs/simulation/robot.html) maybe you can look at that codebase to add customized robots.

**Comment by chiawenwang** [comment]
Ok! Thank you for replying! We have figured out by following Open-Teach!
