### ISSUE TITLE
Understanding the state and action spaces of demonstration data

### ISSUE THREAD

**Issue by Mr-vedant-gupta** [Lifelong-Robot-Learning/LIBERO#26]
Hi!

I'm trying to understand what exactly the different keys in the image below represent:
<img width="590" alt="Screenshot 2024-07-31 at 3 06 00 PM" src="https://github.com/user-attachments/assets/462b8ba4-13e1-4490-8a72-ad0ec4e0adae">

Regarding the action space - my understanding is that the first 6 variables represent the desired change in position and orientation of the gripper, while the last variable represents whether it is open or closed. Does this mean that the action space is Markov given the robot state and image of the environment?

Additionally, could you please help me understand what each of the observation keys represents, and what the key "states" with dimension (T, 47 ) represents?

Thanks!

**Comment by igeorgiev-bdai** [comment]
Hi, did you figure out what the action space is in the end? Is it really change in EE pose?

**Comment by Mr-vedant-gupta** [comment]
Hi @igeorgiev-bdai 
I'm still waiting for a response on this post, but believe the action space is change in EE pose. 
See [here](https://robosuite.ai/docs/modules/controllers.htmlposehttps://robosuite.ai/docs/modules/controllers.html): When using any position-based control (OSC, IK, or JOINT_POSITION controllers), input actions are, by default, interpreted as delta values from the current state. 
Based on some digging through the code I remember the action space being OSC_POSE

**Comment by zhuyifengzju** [comment]
Hi,
The action space is the OSC_POSE. I am not sure what you mean by the action space being Markovian --- Typically we can if a policy is a markovian or the state space is markovian. Can you elaborate on this? 

Regarding the observation keys:
- `XXX_rgb`: The RGB image of camera named under `XXX`
- ee_ori: axis angles of end effectors
- ee_pos: locations of end effectors
- ee_states: the concatenation of ee_pos and ee_ori
- gripper_states: the joint readings of the gripper
- joint_states: joint angle readings of the robot arm


The `states` here refer to the mujoco simulation states, which is useful if you want to directly reset the environment to a specific timeframe. The dimension 47 means that for this task, the number of joints of the entire simulation is 47. For this one, please refer to the mujoco  documentation for more details.

**Comment by YEOMJINSEOP** [comment]
@zhuyifengzju  Thanks for the detailed responses in previous comments. 

I have a question about **robot_states with shape (T, 9).** 
Could you clarify what  9 dimensions represents within this tensor?

Thanks again for the insightful work on this project.

**Comment by zhuyifengzju** [comment]
do you mean the `joint_states`? If that's the case, I believe it's 7 (arm joint states) + 2 (gripper states), but since the gripper joint control is mirrored, the action space is only 1 for the gripper.

**Comment by YEOMJINSEOP** [comment]
> responses in previous comments.

Thanks for reply @zhuyifengzju.

Referring to the image from the issue's initial comment, 
I’m trying to clarify the difference between:

- `robot_states` with shape (329, 9), which is the third line from the bottom.
- several states in `obs` including ee_states, gripper_states, joint states.
![image](https://github.com/user-attachments/assets/f2f2943a-4136-409d-8902-c45c7d64488e)

Based on your previous response, could I interpret `robot_states` with shape (329, 9) as a combination of **joint states** (329, 7) and **gripper states** (329, 2)?

I apologize if my question seems basic, as I am relatively new to robotics research.

Thanks in advance for your clarification!

**Comment by zhuyifengzju** [comment]
Yes, I believe it's correct. It would be safe to double check yourself again (looking at the numericals)

**Comment by GuHuangAI** [comment]
> Hi @igeorgiev-bdai I'm still waiting for a response on this post, but believe the action space is change in EE pose. See [here](https://robosuite.ai/docs/modules/controllers.html): "When using any position-based control (OSC, IK, or JOINT_POSITION controllers), input actions are, by default, interpreted as delta values from the current state" Based on some digging through the code I remember the action space being OSC_POSE
> 
> @Cranial-XIX Apologies for the tag but any info on my question would be very much appreciated as I have some research that depends on this!

Hello, I found that the difference of ee_state of two neighbouring frames was not equal to the corresponding action. Could you explain this?

**Comment by GuHuangAI** [comment]
> Yes, I believe it's correct. It would be safe to double check yourself again (looking at the numericals)

Hello, what dose the action mean? I found that the difference of ee_state of two neighbouring frames was not equal to the corresponding action.

**Comment by Lucky-Light-Sun** [comment]
> Yes, I believe it's correct. It would be safe to double check yourself again (looking at the numericals)

however, i checked this, maybe the `robot states` is no the concat of `gripper_states` and `joint_states`.

![Image](https://github.com/user-attachments/assets/589dced7-7757-4657-917b-f6523f8191d2)

**Comment by AnnabellaMacaluso** [comment]
Hi, is there any update on the specifics of what action here represents? It doesn't seem to represent end effector pose because the outputs are not achievable if it's with respect to the robot base. If it's delta pose, often times the scale (which in prior issues was mentioned to be meters) doesn't translate correctly (for instance 0.3 m corresponds to 0.03 m in movement in sim), any clarification on this would be greatly appreciated, thank you so much.

**Comment by WwZzz** [comment]
> Hi, is there any update on the specifics of what action here represents? It doesn't seem to represent end effector pose because the outputs are not achievable if it's with respect to the robot base. If it's delta pose, often times the scale (which in prior issues was mentioned to be meters) doesn't translate correctly (for instance 0.3 m corresponds to 0.03 m in movement in sim), any clarification on this would be greatly appreciated, thank you so much.

The actions[:6] will be scaled by [0.05 0.05 0.05 0.5  0.5  0.5] in robosuite and then be used to compute the `goal_pos=current_pos+scaled_action` in `robosuite`. After obtaining the `goal_pos`, mujoco will try to approach the `goal_pos` by PID controling based on the controlling frequency, most of which won't actually reach the target pos.

**Comment by WwZzz** [comment]
> > Yes, I believe it's correct. It would be safe to double check yourself again (looking at the numericals)
> 
> Hello, what dose the action mean? I found that the difference of ee_state of two neighbouring frames was not equal to the corresponding action.

It's a scaled version of the delta of pos and ori. The scaled delta of poses won't be absolutely reached when controlling the robot.
