### ISSUE TITLE
Adding depth to demo datasets

### ISSUE THREAD

**Issue by Aryan9101** [Lifelong-Robot-Learning/LIBERO#29]
Hello, the current demo datasets don't include any depth maps. How should I go about recreating the dataset so it has depth maps as an observation along with the rgb images? Thanks!

**Comment by prinshul** [comment]
@Cranial-XIX Same question!

**Comment by yasibot8** [comment]
Same question!

**Comment by yasibot8** [comment]
> Hello, the current demo datasets don't include any depth maps. How should I go about recreating the dataset so it has depth maps as an observation along with the rgb images? Thanks!

Did you get?

**Comment by zhuyifengzju** [comment]
Hi, robosuite documentation will be updated soon with more detailed description. For now, I am providing the most critical parts that are relevant:
https://github.com/ARISE-Initiative/robosuite/blob/74981fd347660205efb4f8c0005e28ec621f5304/robosuite/environments/robot_env.py#L140

convert to a metric depth map: https://github.com/ARISE-Initiative/robosuite/blob/74981fd347660205efb4f8c0005e28ec621f5304/robosuite/utils/camera_utils.py#L106

After camera_depth is enabled, you should be able to see a key in `obs` named `CAMERA_NAME_depth`.

**Comment by AndyCao1125** [comment]
@zhuyifengzju 
Hi! I have a question regarding the depth output when setting `camera_depth=True` in the Libero environment (e.g., goal, 10). According to the [RoboSuite depth documentation](https://robosuite.ai/docs/modules/renderers.html?highlight=depth), this should return normalized depth values in the range of [0, 1]. However, the observed depth values are roughly between [0.98, 0.99], resulting in a near-white image unless normalized.

Could you clarify whether the depth images returned in the Libero environment are raw metric depth or normalized depth? If they are raw depth values, what are their units, and how can I obtain the minimum and maximum depth information that the depth camera can capture?

Thanks!

**Comment by ZeyuPing** [comment]
@AndyCao1125 Hi! Could you please offer me some codes for reference? I still don't know how to replay it T_T
