### ISSUE TITLE
An issue about dataset.

### ISSUE THREAD

**Issue by Zhangwenyao1** [Lifelong-Robot-Learning/LIBERO#30]
Thanks for your great work!
Are there any segmentation masks and depth in your dataset.

**Comment by Cranial-XIX** [comment]
Thanks for your interest in our work, currently we do not have these in our datasets. But those are provided in Robosuite, so I believe if you re-rollout the dataset you can get the mask/depth from the simulator.

**Comment by Zhangwenyao1** [comment]
> Thanks for your interest in our work, currently we do not have these in our datasets. But those are provided in Robosuite, so I believe if you re-rollout the dataset you can get the mask/depth from the simulator.

Thanks for your reply.
Can you tell me how to re-rollout the dataset？
Are there any tutorials ?

**Comment by Cranial-XIX** [comment]
You can take a look at our README page. Basically, you choose a task, set the initial state, and then simulate the action, and then get the observation with depth/mask.

**Comment by Zhangwenyao1** [comment]
> You can take a look at our README page. Basically, you choose a task, set the initial state, and then simulate the action, and then get the observation with depth/mask.

Thanks for your quick reply!
Best wishes!

**Comment by JustinKai0527** [comment]
@Cranial-XIX @Zhangwenyao1 can you provide the instruction to re-rollout the dataset
